#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY . .
RUN dotnet restore "./4_GraphQL/GraphQL.csproj"
COPY . .
WORKDIR "/src/."

RUN dotnet build "./4_GraphQL/GraphQL.csproj" -c Release -o /app/build
WORKDIR "/src/4_GraphQL"

FROM build AS publish
RUN dotnet publish "GraphQL.csproj" -c Release -o /app/publish /p:UseWebAPI=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
RUN mkdir -p /app/certificates
RUN mkdir -p /app/CDN
RUN mkdir -p /app/Font
RUN mkdir -p /app/Log

COPY 4_GraphQL/certificates/https.aspnetapp.pfx /app/certificates/

ENTRYPOINT ["dotnet", "GraphQL.dll"]
